package com.desafioitau.api.transferencia.v1.conta.exception;

public class ContaInternalServerErrorException extends ContaException {
    public ContaInternalServerErrorException(Throwable cause) {
        super(cause);
    }
}
