package com.desafioitau.api.transferencia.exceptions.conta.exception;

public class ContaInternalServerErrorException extends ContaException {
    public ContaInternalServerErrorException(Throwable cause) {
        super(cause);
    }
}
