package com.desafioitau.api.transferencia.exceptions.cliente.exception;

public class ClienteInternalErrorException extends ClienteException {
    public ClienteInternalErrorException(Throwable cause) {
        super(cause);
    }
}
